services:
    mysql:
        build:
            context: docker/mysql
            dockerfile: Dockerfile
            platforms:
                - "linux/amd64"
            tags:
                - "java_bc12_capstone/mysql:1.0.0"

        container_name: java_bc12_capstone_be_mysql

        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

        networks:
            - mysql

        ports:
            - "${MYSQL_PORT}:${MYSQL_PORT}"

        volumes:
            - mysql:/var/lib/mysql

        restart: on-failure

        healthcheck:
            test: [ "CMD-SHELL", "/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute \"SHOW DATABASES;\" || exit 1" ]
            interval: 5s
            timeout: 3s
            retries: 3

        deploy:
            mode: global

            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
                max_attempts: 3

            resources:
                limits:
                    cpus: "4"
                    memory: 4096M
                reservations:
                    cpus: "4"
                    memory: 2048M

volumes:
    mysql:
        driver: local
        labels:
            com.ndt.capstone.description: "Backend Database"

networks:
    mysql:
        driver: bridge
