services:
    mysql:
        build:
            context: docker/mysql
            dockerfile: Dockerfile
            platforms:
                - "linux/amd64"
            tags:
                - "java_bc12_capstone/mysql:1.0.0"

        container_name: java_bc12_capstone_be_mysql

        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

        networks:
            - mysql

        ports:
            - "${MYSQL_PORT}:${MYSQL_PORT}"

        volumes:
            - mysql:/var/lib/mysql

        restart: on-failure

        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

        deploy:
            mode: global

            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
                max_attempts: 3

            resources:
                limits:
                    cpus: "4"
                    memory: 4096M
                reservations:
                    cpus: "4"
                    memory: 2048M

    redis:
        image: redis:8.8.1-alpine
        container_name: java_bc12_capstone_be_redis
        environment:
            REDIS_PORT: ${REDIS_PORT}
        networks:
            - mysql
            - redis
        ports:
            - "${REDIS_PORT}:${REDIS_PORT}"
        command:
            - redis-server
            - --appendonly
            - "yes"
            - --requirepass
            - ${REDIS_PASSWORD}"
        restart: on-failure
        volumes:
            - redis:/data

    redisinsight:
        image: redis/redisinsight:3.8
        container_name: java_bc12_capstone_be_redisinsight
        ports:
            - "${REDIS_UI_PORT}:${REDIS_UI_PORT}"
        restart: on-failure
        volumes:
            - redisinsight:/data
        networks:
            - redis

    kafka:
        image: confluentinc/cp-kafka:7.9.1
        hostname: kafka
        container_name: java_bc12_capstone_be_kafka
        ports:
            - "9092:9092"
            - "9093:9093"
            - "9094:9094"
        environment:
            KAFKA_KRAFT_MODE: "true"
            KAFKA_PROCESS_ROLES: controller,broker
            KAFKA_NODE_ID: 1
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
            KAFKA_LOG_DIRS: /var/lib/kafka/data
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_LOG_RETENTION_HOURS: 168
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            CLUSTER_ID: "Mk30EYBSD34fcwNTJENDM2Qk"
            KAFKA_MESSAGE_MAX_BYTES: 10485760
            KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
            KAFKA_HEAP_OPTS: "-Xmx2G -Xms2G"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./kafka_data:/var/lib/kafka/data
        networks:
            - mysql

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: java_bc12_capstone_be_kafka-ui-corporate
        ports:
            - "8085:8080"
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
        networks:
            - mysql
volumes:
    mysql:
        driver: local
        labels:
            com.ndt.capstone.description: "Backend Database"
    redis:
        driver: local
        labels:
            com.ndt.capstone.description: "Redis Cache Database"
    redisinsight:
        driver: local
        labels:
            com.ndt.capstone.description: "Redis Cache Database"
    kafka_data:
        driver: local
        labels:
            com.ndt.capstone.description: "Kafka Cache Database"
networks:
    mysql:
        driver: bridge
    redis:
        driver: bridge
