server:
    port: 8080

spring:
    config:
        import: "optional:file:.env.prod[.properties]"

    devtools:
        restart:
            enabled: false

jwt:
    expiration: 900000 # 15 mins

debug: false
