spring:
    application:
        name: capstone

    config:
        import: "optional:file:.env[.properties]"

    datasource:
        url: jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}

    jpa:
        generate-ddl: true
        hibernate.ddl-auto: none

    devtools:
        restart:
            enabled: true

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}    # Thay bằng email của người gửi trong .env
        password: ${MAIL_PASSWORD}     # Thay bằng App Password trong .env
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

jwt:
    secret: LTKw1Ba/s6nM6PoClDdEwk68UZ7cMBuqNGARAGIFowU=
    expiration: 600000
