spring:
    application:
        name: capstone

    config:
        import: "optional:file:.env[.properties]"

    datasource:
        url: jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}?connectionTimeZone=Asia/Ho_Chi_Minh&forceConnectionTimeZoneToSession=true
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
    
    jpa:
        show-sql: false
        generate-ddl: true

        hibernate:
            ddl-auto: none

        properties:
            hibernate:
                format_sql: true
                highlight_sql: true


    devtools:
        restart:
            enabled: true
    data:
        web:
            pageable:
                default-page-size: 20
                max-page-size: 100
                one-indexed-parameters: false   # if true, page starts at 1 instead of 0
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            password: ${REDIS_PASSWORD}
            timeout: 5000ms

#    cache:
#        type:
#            redis:
#                time-to-live: 100000        # ms — entries auto-expire after 10 min
#                cache-null-values: false
#                key-prefix: "products::"
#                use-key-prefix: true

server:
    address: localhost
    port: ${APPLICATION_PORT}

jwt:
    secret: LTKw1Ba/s6nM6PoClDdEwk68UZ7cMBuqNGARAGIFowU=
    #    expiration: 900000 # 15 mins
    expiration: 86400000 # 15 mins

auth:
    max-attempt: 3
    lock-duration: 900000 # 15 mins

file:
    root: ${DATA_ROOT}

    upload:
        image:
            path: ${UPLOAD_IMAGE_PATH}
            default-image-name: ${DEFAULT_VARIANT_IMAGE_NAME}

cache:
    product:
        prefix: product
        all:
            cache-duration: 900000 # 15 mins

    brand:
        prefix: brand
        all:
            cache-duration: 900000 # 15 mins

    color:
        prefix: color
        all:
            cache-duration: 900000 # 15 mins

    size:
        prefix: size
        all:
            cache-duration: 900000 # 15 mins

    country:
        prefix: country
        all:
            cache-duration: 900000 # 15 mins

    payment:
        method:
            prefix: payment_method
            all:
                cache-duration: 900000 # 15 mins

        exchange:
            prefix: exchange_rate
    account:
        prefix: account

management:
    endpoints:
        web:
            exposure:
                include: health
    endpoint:
        health:
            show-details: always

payment:
    bank-transfer:
        bank-id: ${VIETQR_BANK_ID}
        account-no: ${VIETQR_ACCOUNT_NO}
        account-name: ${VIETQR_ACCOUNT_NAME}

    exchange:
        base-currency: USD
        fallback-rate: 27000
        refresh-interval: 7200000  # 1 day
        api-url: https://api.exchangerate-api.com/v4/latest/

    vietqr:
        url: https://img.vietqr.io/image

    pending-timeout: 120  # seconds
