spring:
    config:
        import: "optional:file:.env.dev[.properties]"

    jpa:
        show-sql: false

        hibernate:
            ddl-auto: validate

jwt:
    expiration: 86400000 # 24 hours

debug: false
